export const skills:any=[
    "JavaScript",
    "TypeScript",
    "Node.js",
    "Express",
    "React.js",
    "Next.js",
    "MongoDB",
    "GraphQL",
    "Web socket",
    "Jest",
    "Python",
    "Java",
    "C++",
    "C",
    "Redux",
    "jQuery",
    "NoSQL",
    "Git",
    "Microservices",
    "Keycloak",
    "Docker",
    "Redis",
    "Nginx",
    "Algolia",
    "AWS",
    "Vercel",
    "Bootstrap",
    "Firebase",
    "SASS",
    "Unity 3D",
    "Auth0",
    "Jira",
    "C#",
    "REST APIs",
    "Linux",
    "PostgreSQL",
    "WebRTC",
    "EJS",
    "Handlebars",
    "Netlify"
]